### ISSUE TITLE
Token 'disable' is an unexpected token at column 11 of the expression

### ISSUE THREAD

**Issue by sujithtomy** [jfmdev/ngComboDatePicker#14]
AngularJS v1.3.15

Following error comes up while intrgrating to my application.

```
angular.js:11655 Error: [$parse:syntax] Syntax Error: Token 'disable' is an unexpected token at column 11 of the expression [date.name disable when date.disabled] starting at [disable when date.disabled].
http://errors.angularjs.org/1.3.15/$parse/syntax?p0=disable&p1=is%20an%20unexpected%20token&p2=11&p3=date.nameNaNisable%20when%date.disabled&p4=disable%20when%date.disabled
    at https://localhost:44347/Scripts/angular.js:63:12
    at Parser.throwError (https://localhost:44347/Scripts/angular.js:12070:11)
    at Parser.parse (https://localhost:44347/Scripts/angular.js:12023:12)
    at $parse (https://localhost:44347/Scripts/angular.js:12737:39)
    at setupAsOptions (https://localhost:44347/Scripts/angular.js:25795:25)
    at link (https://localhost:44347/Scripts/angular.js:25719:23)
    at invokeLinkFn (https://localhost:44347/Scripts/angular.js:8258:9)
    at nodeLinkFn (https://localhost:44347/Scripts/angular.js:7768:11)
    at compositeLinkFn (https://localhost:44347/Scripts/angular.js:7117:13)
    at nodeLinkFn (https://localhost:44347/Scripts/angular.js:7763:24)
```

**Comment by jfmdev** [comment]
Hi, and thank you for using this library.
Starting version [1.2.1](https://github.com/jfmdev/ngComboDatePicker/releases/tag/v1.2.1) (i.e. after the implementation of placeholders), ngComboDatePicker requires AngularJS v1.4.0 or greater (sorry if I did not mentioned this before).
So you should update Angular to a newer version or use the version [1.2.0](https://github.com/jfmdev/ngComboDatePicker/releases/tag/v1.2.0)
